service:
  name: easy-admin # 服务名称
  addr: :8080  #服务地址
  debug: true  #是否开启debug
  errorCode: 400 #默认失败的code
  successCode: 200 #默认成功的code
  title: easy-admin 后台管理系统 #系统名称
  desc: 开放协作，拥抱未来，插件化编程实现 #系统描述
  copyright: Copyright © 2023 lime.qlime.cn. All rights reserved. #版权信息
  staticUrl: http://localhost:8080  #静态资源url
  logo: http://p3-armor.byteimg.com/tos-cn-i-49unhts6dw/dfdba5317c0c20ce20e64fac803d52bc.svg~tplv-49unhts6dw-image.image #系统logo
  topMenu: false
# 日志相关配置
log:
  header: trace-id # 当请求头存在trace-id时，优先使用
  field: trace-id # 链路日志字段名
  level: 0 #日志输出等级
  output:
    - stdout # stdout:控制台输出，k8s日志收集
    - file # file:输出到文件
  file: #output存在file时此配置才可生效
    name: ./tmp/runtime/output.log #日志存放地址
    maxSize: 1 #日志文件最大容量,单位m
    maxBackup: 5 #日志文件最多保存个数
    maxAge: 1 #保留就文件的最大天数,单位天
    compress: false #是否进行压缩归档